var exerciciosPorGrupo = {
  todos: [
    "Supino Reto Barra",
    "Supino Inclinado Barra",
    "Supino Declinado Barra",
    "Supino Reto Barra Smith",
    "Supino Inclinado Barra Smith",
    "Supino Declinado Barra Smith",
    "Supino Reto Halter",
    "Supino Inclinado Halter",
    "Supino Declinado Halter",
    "Supino Reto Barra Pg.Fechada",
    "Supino Inclinado Barra Pg.Fechada",
    "Supino Declinado Barra Pg.Fechada",
    "Flexão Solo Aberto",
    "Flexão Solo Fechado",
    "Crucifixo Reto Banco",
    "Crucifixo Inclinado Banco",
    "Crucifixo Declinado Banco",
    "Crucifixo Reto PeckDeck",
    "Crucifixo Cross P.Alta",
    "Crucifixo Cross P.Média",
    "Crucifixo Cross P.Baixa",
    "Crucifixo Inverso Halter",
    "Crucifixo Inverso Banco Inclinado",
    "Crucifixo Inverso PeckDeck",
    "Crucifixo Inverso Cross P.Alta",
    "Crucifixo Inverso Cross P.Média",
    "Crucifixo Inverso Cross P.Baixa",
    "Elevação Frontal Banco Inclinado",
    "Mergulho Paralela",
    "Puxada Aberta Pronada",
    "Puxada Fechada Supinada",
    "Puxada Neutra Triângulo",
    "Puxada Neutra Romana",
    "Remada Baixa Triângulo",
    "Remada Baixa Fechada Supinada",
    "Remada Alta Sentado Pronada",
    "Remada Baixa Romana",
    "Remada Curvada Supinada",
    "Remada Curvada Pronada",
    "Remada Cavalinho Barra",
    "Remada Cavalinho Polia Baixa",
    "Barra Fixa Pronada",
    "Barra Fixa Supinada",
    "Barra Fixa Neutra",
    "Serrote Halter",
    "Serrote Polia Média",
    "Serrote Polia Baixa",
    "Remada Alta Vertical Fechada",
    "Remada Alta Vertical Aberta",
    "Encolhimento Halter",
    "Encolhimento Barra Anterior",
    "Encolhimento Barra Posterior",
    "Encolhimento Barra Anterior Smith",
    "Encolhimento Barra Posterior Smith",
    "Encolhimento Barra Anterior Cross",
    "Encolhimento Barra Posterior Cross",
    "PullDown Cross",
    "PullOver Halter",
    "PullFace Cross",
    "Elevação Lateral Halter",
    "Elevação Lateral Cross",
    "Elevação Frontal Halter Martelo",
    "Elevação Frontal Halter Pronada",
    "Elevação Frontal Barra Pronada",
    "Elevação Frontal Halter Supinada",
    "Elevação Frontal Barra Supinada",
    "Elevação Frontal Cross Pronada",
    "Elevação Frontal Cross Supinada",
    "Elevação Frontal Cross Corda",
    "Desenvolvimento Halter Aberto",
    "Desenvolvimento Halter Fechado",
    "Desenvolvimento Barra",
    "Desenvolvimento Barra Smith",
    "Desenvolvimento Arnold",
    "Rotação Interna Ombro Polia",
    "Rotação Externa Ombro Polia",
    "Rotação Ombro Halter Em Pé",
    "Rotação Ombro Halter Deitado",
    "Tríceps Francês Halter",
    "Tríceps Francês Polia",
    "Tríceps Polia Barra",
    "Tríceps Polia Corda",
    "Tríceps Testa Barra",
    "Tríceps Testa Halter",
    "Tríceps Testa Polia",
    "Tríceps Coice Halter",
    "Tríceps Coice Polia",
    "Tríceps Coice Polia Dupla Corda",
    "Rosca Direta Halter",
    "Rosca Alternada Halter",
    "Rosca Direta Barra",
    "Rosca Direta Polia",
    "Bíceps Scott Barra",
    "Bíceps Scott Halter",
    "Bíceps Concentrada Scott",
    "Bíceps Concentrada Perna",
    "Bíceps Martelo Halter",
    "Bíceps Alternada Martelo",
    "Bíceps Martelo Barra Romana",
    "Bíceps Martelo Polia Corda",
    "Bíceps Martelo Banco Inclinado",
    "Rosca Direta Banco Inclinado",
    "Rosca Alternada Banco Inclinado",
    "Bíceps Dupla Polia Alta",
    "LegPress 45° Pés Altos",
    "LegPress 45° Pés Baixos",
    "LegPress 45° Sumô",
    "LegPress 45° Unilateral",
    "Agachamento Hack",
    "Agachamento Smith",
    "Agachamento Livre Barra",
    "Agachamento Livre Halter Frente",
    "Agachamento Livre Halter Paralelo",
    "Afundo Halter",
    "Afundo Smith",
    "Afundo Barra",
    "Búlgaro",
    "Sumô Barra",
    "Sumô Halter",
    "Sumô Smith",
    "Cadeira Flexora",
    "Cama Flexora",
    "Cadeira Extensora",
    "Cadeira Adutora",
    "Cadeira Abdutora",
    "Elevação Pélvica Barra",
    "Elevação Pélvica Máquina",
    "Levantamento Terra",
    "Levantamento Terra Sumô",
    "Apolete Extensão Quadril",
    "Apolete Flexão Quadril",
    "Apolete Abdução Quadril",
    "Apolete Adução Quadril",
    "Stiff Barra",
    "Stiff Halter",
    "Glúteo Polia Coice",
    "Glúteo 4 Apoio",
    "Abdominal Supra Solo",
    "Abdominal Supra Declinado",
    "Abdominal Infra",
    "Abdominal Infra Alternado",
    "Abdominal Remador",
    "Abdominal Arranca Bucho",
    "Abdominal Infra Paralela",
    "HiperExtensão Lombar",
    "HiperExtensão Ombro",
  ],
  dorsal: [
    "Puxada Aberta Pronada",
    "Puxada Fechada Supinada",
    "Puxada Neutra Triângulo",
    "Puxada Neutra Romana",
    "Remada Baixa Triângulo",
    "Remada Baixa Fechada Supinada",
    "Remada Alta Sentado Pronada",
    "Remada Baixa Romana",
    "Remada Curvada Supinada",
    "Remada Curvada Pronada",
    "Remada Cavalinho Barra",
    "Remada Cavalinho Polia Baixa",
    "Barra Fixa Pronada",
    "Barra Fixa Supinada",
    "Barra Fixa Neutra",
    "Serrote Halter",
    "Serrote Polia Média",
    "Serrote Polia Baixa",
    "Remada Alta Vertical Fechada",
    "Remada Alta Vertical Aberta",
    "Encolhimento Halter",
    "Encolhimento Barra Anterior",
    "Encolhimento Barra Posterior",
    "Encolhimento Barra Anterior Smith",
    "Encolhimento Barra Posterior Smith",
    "Encolhimento Barra Anterior Cross",
    "Encolhimento Barra Posterior Cross",
    "PullDown Cross",
    "PullOver Halter",
    "PullFace Cross",
  ],
  peitoral: [
    "Supino Reto Barra",
    "Supino Inclinado Barra",
    "Supino Declinado Barra",
    "Supino Reto Barra Smith",
    "Supino Inclinado Barra Smith",
    "Supino Declinado Barra Smith",
    "Supino Reto Halter",
    "Supino Inclinado Halter",
    "Supino Declinado Halter",
    "Supino Reto Barra Pg.Fechada",
    "Supino Inclinado Barra Pg.Fechada",
    "Supino Declinado Barra Pg.Fechada",
    "Flexão Solo Aberto",
    "Flexão Solo Fechado",
    "Crucifixo Reto Banco",
    "Crucifixo Inclinado Banco",
    "Crucifixo Declinado Banco",
    "Crucifixo Reto PeckDeck",
    "Crucifixo Cross P.Alta",
    "Crucifixo Cross P.Média",
    "Crucifixo Cross P.Baixa",
    "Crucifixo Inverso Halter",
    "Crucifixo Inverso Banco Inclinado",
    "Crucifixo Inverso PeckDeck",
    "Crucifixo Inverso Cross P.Alta",
    "Crucifixo Inverso Cross P.Média",
    "Crucifixo Inverso Cross P.Baixa",
    "Elevação Frontal Banco Inclinado",
    "Mergulho Paralela",
  ],
  biceps: [
    "Rosca Direta Halter",
    "Rosca Alternada Halter",
    "Rosca Direta Barra",
    "Rosca Direta Polia",
    "Bíceps Scott Barra",
    "Bíceps Scott Halter",
    "Bíceps Concentrada Scott",
    "Bíceps Concentrada Perna",
    "Bíceps Martelo Halter",
    "Bíceps Alternada Martelo",
    "Bíceps Martelo Barra Romana",
    "Bíceps Martelo Polia Corda",
    "Bíceps Martelo Banco Inclinado",
    "Rosca Direta Banco Inclinado",
    "Rosca Alternada Banco Inclinado",
    "Bíceps Dupla Polia Alta",
  ],
  triceps: [
    "Tríceps Francês Halter",
    "Tríceps Francês Polia",
    "Tríceps Polia Barra",
    "Tríceps Polia Corda",
    "Tríceps Testa Barra",
    "Tríceps Testa Halter",
    "Tríceps Testa Polia",
    "Tríceps Coice Halter",
    "Tríceps Coice Polia",
    "Tríceps Coice Polia Dupla Corda",
  ],
  ombro: [
    "Elevação Lateral Halter",
    "Elevação Lateral Cross",
    "Elevação Frontal Halter Martelo",
    "Elevação Frontal Halter Pronada",
    "Elevação Frontal Barra Pronada",
    "Elevação Frontal Halter Supinada",
    "Elevação Frontal Barra Supinada",
    "Elevação Frontal Cross Pronada",
    "Elevação Frontal Cross Supinada",
    "Elevação Frontal Cross Corda",
    "Desenvolvimento Halter Aberto",
    "Desenvolvimento Halter Fechado",
    "Desenvolvimento Barra",
    "Desenvolvimento Barra Smith",
    "Desenvolvimento Arnold",
    "Rotação Interna Ombro Polia",
    "Rotação Externa Ombro Polia",
    "Rotação Ombro Halter Em Pé",
    "Rotação Ombro Halter Deitado",
  ],
  pernas: [
    "LegPress 45° Pés Altos",
    "LegPress 45° Pés Baixos",
    "LegPress 45° Sumô",
    "LegPress 45° Unilateral",
    "Agachamento Hack",
    "Agachamento Smith",
    "Agachamento Livre Barra",
    "Agachamento Livre Halter Frente",
    "Agachamento Livre Halter Paralelo",
    "Afundo Halter",
    "Afundo Smith",
    "Afundo Barra",
    "Búlgaro",
    "Sumô Barra",
    "Sumô Halter",
    "Sumô Smith",
    "Cadeira Flexora",
    "Cama Flexora",
    "Cadeira Extensora",
    "Cadeira Adutora",
    "Cadeira Abdutora",
    "Elevação Pélvica Barra",
    "Elevação Pélvica Máquina",
    "Levantamento Terra",
    "Levantamento Terra Sumô",
    "Apolete Extensão Quadril",
    "Apolete Flexão Quadril",
    "Apolete Abdução Quadril",
    "Apolete Adução Quadril",
    "Stiff Barra",
    "Stiff Halter",
    "Glúteo Polia Coice",
    "Glúteo 4 Apoio",
  ],
  abdominal: [
    "Abdominal Supra Solo",
    "Abdominal Supra Declinado",
    "Abdominal Infra",
    "Abdominal Infra Alternado",
    "Abdominal Remador",
    "Abdominal Arranca Bucho",
    "Abdominal Infra Paralela",
    "HiperExtensão Lombar",
    "HiperExtensão Ombro",
  ],
};
function mostrarExercicios() {
  var grupoSelecionado = document.getElementById("grupo").value;
  var exercicios = exerciciosPorGrupo[grupoSelecionado];
  var grupoSelect = document.getElementById("grupoSelect");
  var exercicioSelect = document.getElementById("exercicioSelect");

  // Remover o primeiro select
  grupoSelect.style.display = "none";

  // Exibir o segundo select
  exercicioSelect.style.display = "block";

  // Selecionar o segundo select
  var exercicioSelectElement = document.getElementById("exercicio");
  exercicioSelectElement.innerHTML = "";

  // Adicionar as opções do grupo selecionado
  exercicios.forEach(function (exercicio) {
    var option = document.createElement("option");
    option.value = exercicio;
    exercicioSelectElement.appendChild(option);
  });
}
